services:
  webserver:
    platform: linux/amd64
    environment:
      MDC_DBUSER: sa
  db:
    platform: linux/amd64
    image: moodlehq/moodle-db-mssql:${MDC_DB_VERSION}
    environment:
        ACCEPT_EULA: "y"
        SA_PASSWORD: "m@0dl3ing"
