services:
  db:
    image: postgres:${MDC_DB_VERSION}
    command: postgres -c synchronous_commit=off -c full_page_writes=off
    environment:
      POSTGRES_USER: moodle
      POSTGRES_PASSWORD: "m@0dl3ing"
      POSTGRES_DB: moodle
      POSTGRES_INITDB_ARGS: "--no-sync"
