services:
  webserver:
    environment:
      MOODLE_DOCKER_DBTYPE: sqlsrv
      MOODLE_DOCKER_DBUSER: sa
  db:
    image: moodlehq/moodle-db-mssql:${MOODLE_DOCKER_DB_VERSION:-latest}
    environment:
        ACCEPT_EULA: "y"
        SA_PASSWORD: "m@0dl3ing"
    volumes:
      - "${ASSETDIR}/db/mssql_wait.sh:/mdc_db_wait.sh"
      - "${ASSETDIR}/db/mssql_backup.sh:/mdc_db_backup.sh"
      - "${ASSETDIR}/db/mssql_restore.sh:/mdc_db_restore.sh"
