version: "2.4"
services:
  webserver:
    environment:
      MOODLE_DOCKER_DBTYPE: oci
      MOODLE_DOCKER_DBNAME: XE
  db:
    image: moodlehq/moodle-db-oracle-r2:${MOODLE_DOCKER_DB_VERSION:-21}
    volumes:
      - "${ASSETDIR}/db/oracle_wait.sh:/opt/oracle/mdc_db_wait.sh"
      - "${ASSETDIR}/db/oracle_wait.sql:/opt/oracle/mdc_db_wait.sql"
      - "${ASSETDIR}/db/oracle_backup.sh:/opt/oracle/mdc_db_backup.sh"
      - "${ASSETDIR}/db/oracle_restore.sh:/opt/oracle/mdc_db_restore.sh"
